CREATE TABLE "regional_daily_air_quality" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"region_code" text NOT NULL,
	"region_name" text NOT NULL,
	"sido_name" text NOT NULL,
	"measure_date" text NOT NULL,
	"data_time" text NOT NULL,
	"khai_value" text,
	"khai_grade" text,
	"pm10_value" text,
	"pm10_grade" text,
	"pm10_avg" text,
	"pm10_max" text,
	"pm10_min" text,
	"pm25_value" text,
	"pm25_grade" text,
	"pm25_avg" text,
	"pm25_max" text,
	"pm25_min" text,
	"o3_value" text,
	"o3_grade" text,
	"o3_avg" text,
	"o3_max" text,
	"o3_min" text,
	"no2_value" text,
	"no2_grade" text,
	"co_value" text,
	"co_grade" text,
	"so2_value" text,
	"so2_grade" text,
	"cache_key" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"raw_data" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "regional_hourly_air_quality" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"region_code" text NOT NULL,
	"region_name" text NOT NULL,
	"sido_name" text NOT NULL,
	"measure_date" text NOT NULL,
	"measure_hour" integer NOT NULL,
	"data_time" text NOT NULL,
	"khai_value" text,
	"khai_grade" text,
	"pm10_value" text,
	"pm10_grade" text,
	"pm25_value" text,
	"pm25_grade" text,
	"o3_value" text,
	"o3_grade" text,
	"no2_value" text,
	"no2_grade" text,
	"co_value" text,
	"co_grade" text,
	"so2_value" text,
	"so2_grade" text,
	"cache_key" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"raw_data" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
