CREATE TABLE "daily_weather_data" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_key" text NOT NULL,
	"location_name" text NOT NULL,
	"latitude" text,
	"longitude" text,
	"forecast_date" text NOT NULL,
	"day_of_week" text NOT NULL,
	"temperature" integer NOT NULL,
	"high_temp" integer NOT NULL,
	"low_temp" integer NOT NULL,
	"conditions" text NOT NULL,
	"weather_icon" integer,
	"precipitation_probability" integer,
	"rain_probability" integer,
	"day_weather" jsonb,
	"night_weather" jsonb,
	"headline" jsonb,
	"units" text DEFAULT 'metric' NOT NULL,
	"forecast_days" integer DEFAULT 5 NOT NULL,
	"raw_data" jsonb,
	"cache_key" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "hourly_weather_data" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_key" text NOT NULL,
	"location_name" text NOT NULL,
	"latitude" text,
	"longitude" text,
	"forecast_date" text NOT NULL,
	"forecast_hour" integer NOT NULL,
	"forecast_datetime" timestamp NOT NULL,
	"temperature" integer NOT NULL,
	"conditions" text NOT NULL,
	"weather_icon" integer,
	"humidity" integer,
	"precipitation" text,
	"precipitation_probability" integer,
	"rain_probability" integer,
	"wind_speed" integer,
	"units" text DEFAULT 'metric' NOT NULL,
	"raw_data" jsonb,
	"cache_key" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "weather_location_keys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"location_name" text,
	"latitude" text,
	"longitude" text,
	"location_key" text NOT NULL,
	"localized_name" text,
	"country_code" text,
	"administrative_area" text,
	"search_type" text NOT NULL,
	"raw_location_data" jsonb,
	"cache_key" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "weather_location_keys_cache_key_unique" UNIQUE("cache_key")
);
