CREATE TABLE "google_daily_air_quality_data" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"clerk_user_id" text,
	"latitude" text NOT NULL,
	"longitude" text NOT NULL,
	"location_name" text,
	"forecast_date" text NOT NULL,
	"day_of_week" text NOT NULL,
	"pm10" integer,
	"pm10_max" integer,
	"pm10_min" integer,
	"pm25" integer,
	"pm25_max" integer,
	"pm25_min" integer,
	"cai_kr" integer,
	"cai_kr_max" integer,
	"cai_kr_min" integer,
	"breezo_meter_aqi" integer,
	"breezo_meter_aqi_max" integer,
	"breezo_meter_aqi_min" integer,
	"no2" integer,
	"o3" integer,
	"so2" integer,
	"co" integer,
	"units" text DEFAULT 'metric' NOT NULL,
	"forecast_days" integer DEFAULT 7 NOT NULL,
	"raw_data" jsonb,
	"cache_key" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "google_hourly_air_quality_data" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"clerk_user_id" text,
	"latitude" text NOT NULL,
	"longitude" text NOT NULL,
	"location_name" text,
	"forecast_date" text NOT NULL,
	"forecast_hour" integer NOT NULL,
	"forecast_datetime" timestamp NOT NULL,
	"pm10" integer,
	"pm25" integer,
	"cai_kr" integer,
	"breezo_meter_aqi" integer,
	"no2" integer,
	"o3" integer,
	"so2" integer,
	"co" integer,
	"units" text DEFAULT 'metric' NOT NULL,
	"raw_data" jsonb,
	"cache_key" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
