import { pgTable, unique, uuid, text, boolean, integer, timestamp, foreignKey, jsonb, index } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const userLocations = pgTable("user_locations", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	clerkUserId: text("clerk_user_id").notNull(),
	latitude: text().notNull(),
	longitude: text().notNull(),
	address: text(),
	cityName: text("city_name"),
	isDefault: boolean("is_default").default(true).notNull(),
	nickname: text(),
	accuracy: integer(),
	source: text().default('gps').notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("user_locations_clerk_user_id_unique").on(table.clerkUserId),
]);

export const kakaoResponses = pgTable("kakao_responses", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	messageId: uuid("message_id").notNull(),
	response: text().notNull(),
	responseType: text("response_type").default('text'),
	adminUserId: text("admin_user_id").notNull(),
	sentAt: timestamp("sent_at", { mode: 'string' }).defaultNow().notNull(),
	isSuccessful: boolean("is_successful").default(false),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.messageId],
			foreignColumns: [kakaoMessages.id],
			name: "kakao_responses_message_id_kakao_messages_id_fk"
		}),
]);

export const webhookLogs = pgTable("webhook_logs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	method: text().notNull(),
	url: text().notNull(),
	userAgent: text("user_agent"),
	requestBody: text("request_body"),
	requestHeaders: jsonb("request_headers"),
	statusCode: text("status_code").notNull(),
	responseBody: text("response_body"),
	processingTime: text("processing_time"),
	errorMessage: text("error_message"),
	ipAddress: text("ip_address"),
	isSuccessful: boolean("is_successful").default(true),
	timestamp: timestamp({ mode: 'string' }).defaultNow().notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const kakaoMessages = pgTable("kakao_messages", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	userKey: text("user_key").notNull(),
	message: text().notNull(),
	messageType: text("message_type").default('text'),
	channelId: text("channel_id").default('68bef0501c4ef66e4f5d73be').notNull(),
	receivedAt: timestamp("received_at", { mode: 'string' }).defaultNow().notNull(),
	rawData: jsonb("raw_data"),
	isRead: boolean("is_read").default(false),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	aiResponse: text("ai_response"),
	responseType: text("response_type").default('chatgpt'),
	processingTime: text("processing_time"),
});

export const scheduledMessages = pgTable("scheduled_messages", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	title: text().notNull(),
	message: text().notNull(),
	scheduleType: text("schedule_type").notNull(),
	scheduleTime: text("schedule_time").notNull(),
	scheduleDay: integer("schedule_day"),
	timezone: text().default('Asia/Seoul').notNull(),
	targetType: text("target_type").default('all').notNull(),
	targetUsers: jsonb("target_users"),
	isActive: boolean("is_active").default(true).notNull(),
	lastSentAt: timestamp("last_sent_at", { mode: 'string' }),
	nextSendAt: timestamp("next_send_at", { mode: 'string' }).notNull(),
	totalSentCount: integer("total_sent_count").default(0).notNull(),
	createdBy: text("created_by").notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const scheduledMessageLogs = pgTable("scheduled_message_logs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	scheduledMessageId: uuid("scheduled_message_id").notNull(),
	sentAt: timestamp("sent_at", { mode: 'string' }).defaultNow().notNull(),
	recipientCount: integer("recipient_count").notNull(),
	successCount: integer("success_count").notNull(),
	failureCount: integer("failure_count").default(0).notNull(),
	errorMessage: text("error_message"),
	isSuccessful: boolean("is_successful").default(true).notNull(),
	executionTime: integer("execution_time"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.scheduledMessageId],
			foreignColumns: [scheduledMessages.id],
			name: "scheduled_message_logs_scheduled_message_id_scheduled_messages_"
		}),
]);

export const userSelectedStations = pgTable("user_selected_stations", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	clerkUserId: text("clerk_user_id").notNull(),
	stationName: text("station_name").notNull(),
	sido: text().notNull(),
	isAutoSelected: boolean("is_auto_selected").default(false).notNull(),
	distance: integer(),
	stationAddress: text("station_address"),
	userLatitude: text("user_latitude"),
	userLongitude: text("user_longitude"),
	isDefault: boolean("is_default").default(true).notNull(),
	selectedAt: timestamp("selected_at", { mode: 'string' }).defaultNow().notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("user_selected_stations_clerk_user_id_unique").on(table.clerkUserId),
]);

export const regionalDailyAirQuality = pgTable("regional_daily_air_quality", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	regionCode: text("region_code").notNull(),
	regionName: text("region_name").notNull(),
	sidoName: text("sido_name").notNull(),
	measureDate: text("measure_date").notNull(),
	dataTime: text("data_time").notNull(),
	khaiValue: text("khai_value"),
	khaiGrade: text("khai_grade"),
	pm10Value: text("pm10_value"),
	pm10Grade: text("pm10_grade"),
	pm10Avg: text("pm10_avg"),
	pm10Max: text("pm10_max"),
	pm10Min: text("pm10_min"),
	pm25Value: text("pm25_value"),
	pm25Grade: text("pm25_grade"),
	pm25Avg: text("pm25_avg"),
	pm25Max: text("pm25_max"),
	pm25Min: text("pm25_min"),
	o3Value: text("o3_value"),
	o3Grade: text("o3_grade"),
	o3Avg: text("o3_avg"),
	o3Max: text("o3_max"),
	o3Min: text("o3_min"),
	no2Value: text("no2_value"),
	no2Grade: text("no2_grade"),
	coValue: text("co_value"),
	coGrade: text("co_grade"),
	so2Value: text("so2_value"),
	so2Grade: text("so2_grade"),
	cacheKey: text("cache_key").notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	rawData: jsonb("raw_data"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const regionalHourlyAirQuality = pgTable("regional_hourly_air_quality", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	regionCode: text("region_code").notNull(),
	regionName: text("region_name").notNull(),
	sidoName: text("sido_name").notNull(),
	measureDate: text("measure_date").notNull(),
	measureHour: integer("measure_hour").notNull(),
	dataTime: text("data_time").notNull(),
	khaiValue: text("khai_value"),
	khaiGrade: text("khai_grade"),
	pm10Value: text("pm10_value"),
	pm10Grade: text("pm10_grade"),
	pm25Value: text("pm25_value"),
	pm25Grade: text("pm25_grade"),
	o3Value: text("o3_value"),
	o3Grade: text("o3_grade"),
	no2Value: text("no2_value"),
	no2Grade: text("no2_grade"),
	coValue: text("co_value"),
	coGrade: text("co_grade"),
	so2Value: text("so2_value"),
	so2Grade: text("so2_grade"),
	cacheKey: text("cache_key").notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	rawData: jsonb("raw_data"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const weeklyAirQualityForecasts = pgTable("weekly_air_quality_forecasts", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	dataTime: text("data_time").notNull(),
	informCode: text("inform_code").notNull(),
	informData: text("inform_data").notNull(),
	searchDate: text("search_date").notNull(),
	informOverall: text("inform_overall").notNull(),
	informCause: text("inform_cause"),
	informGrade: text("inform_grade"),
	actionKnack: text("action_knack"),
	dailyForecasts: jsonb("daily_forecasts"),
	imageUrls: jsonb("image_urls"),
	rawData: jsonb("raw_data"),
	cacheKey: text("cache_key").notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const googleDailyAirQualityData = pgTable("google_daily_air_quality_data", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	clerkUserId: text("clerk_user_id"),
	latitude: text().notNull(),
	longitude: text().notNull(),
	locationName: text("location_name"),
	forecastDate: text("forecast_date").notNull(),
	dayOfWeek: text("day_of_week").notNull(),
	pm10: integer(),
	pm10Max: integer("pm10_max"),
	pm10Min: integer("pm10_min"),
	pm25: integer(),
	pm25Max: integer("pm25_max"),
	pm25Min: integer("pm25_min"),
	caiKr: integer("cai_kr"),
	caiKrMax: integer("cai_kr_max"),
	caiKrMin: integer("cai_kr_min"),
	breezoMeterAqi: integer("breezo_meter_aqi"),
	breezoMeterAqiMax: integer("breezo_meter_aqi_max"),
	breezoMeterAqiMin: integer("breezo_meter_aqi_min"),
	no2: integer(),
	o3: integer(),
	so2: integer(),
	co: integer(),
	units: text().default('metric').notNull(),
	forecastDays: integer("forecast_days").default(7).notNull(),
	rawData: jsonb("raw_data"),
	cacheKey: text("cache_key").notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const googleHourlyAirQualityData = pgTable("google_hourly_air_quality_data", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	clerkUserId: text("clerk_user_id"),
	latitude: text().notNull(),
	longitude: text().notNull(),
	locationName: text("location_name"),
	forecastDate: text("forecast_date").notNull(),
	forecastHour: integer("forecast_hour").notNull(),
	forecastDatetime: timestamp("forecast_datetime", { mode: 'string' }).notNull(),
	pm10: integer(),
	pm25: integer(),
	caiKr: integer("cai_kr"),
	breezoMeterAqi: integer("breezo_meter_aqi"),
	no2: integer(),
	o3: integer(),
	so2: integer(),
	co: integer(),
	units: text().default('metric').notNull(),
	rawData: jsonb("raw_data"),
	cacheKey: text("cache_key").notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const apiCallLogs = pgTable("api_call_logs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	apiProvider: text("api_provider").notNull(),
	apiEndpoint: text("api_endpoint").notNull(),
	httpMethod: text("http_method").default('GET').notNull(),
	callDate: text("call_date").notNull(),
	callTime: timestamp("call_time", { mode: 'string' }).defaultNow().notNull(),
	httpStatus: integer("http_status"),
	responseTime: integer("response_time"),
	isSuccessful: boolean("is_successful").default(true).notNull(),
	userId: text("user_id"),
	requestParams: jsonb("request_params"),
	errorMessage: text("error_message"),
	userAgent: text("user_agent"),
	ipAddress: text("ip_address"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const dailyApiStats = pgTable("daily_api_stats", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	statDate: text("stat_date").notNull(),
	apiProvider: text("api_provider").notNull(),
	totalCalls: integer("total_calls").default(0).notNull(),
	successfulCalls: integer("successful_calls").default(0).notNull(),
	failedCalls: integer("failed_calls").default(0).notNull(),
	avgResponseTime: integer("avg_response_time"),
	maxResponseTime: integer("max_response_time"),
	minResponseTime: integer("min_response_time"),
	endpointStats: jsonb("endpoint_stats"),
	hourlyStats: jsonb("hourly_stats"),
	lastUpdated: timestamp("last_updated", { mode: 'string' }).defaultNow().notNull(),
	isFinalized: boolean("is_finalized").default(false).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const userRoles = pgTable("user_roles", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	clerkUserId: text("clerk_user_id").notNull(),
	role: text().default('customer').notNull(),
	permissions: jsonb(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("user_roles_clerk_user_id_key").on(table.clerkUserId),
]);

export const marts = pgTable("marts", {
	id: uuid().primaryKey().notNull(),
	name: text().notNull(),
	description: text(),
	region: text().notNull(),
	address: text(),
	phone: text(),
	email: text(),
	website: text(),
	latitude: text(),
	longitude: text(),
	isVerified: boolean("is_verified").default(false),
	isFastResponse: boolean("is_fast_response").default(false),
	isBusinessRegistered: boolean("is_business_registered").default(false),
	hireCount: integer("hire_count").default(0),
	responseTime: text("response_time").default('24시간'),
	portfolioCount: integer("portfolio_count").default(0),
	photoCount: integer("photo_count").default(0),
	logoUrl: text("logo_url"),
	portfolioUrls: jsonb("portfolio_urls"),
	photoUrls: jsonb("photo_urls"),
	createdBy: text("created_by"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const martDiscounts = pgTable("mart_discounts", {
	id: uuid().primaryKey().notNull(),
	martId: uuid("mart_id").notNull(),
	title: text().notNull(),
	description: text(),
	startDate: timestamp("start_date", { mode: 'string' }),
	endDate: timestamp("end_date", { mode: 'string' }),
	discountRate: text("discount_rate"),
	imageUrl: text("image_url"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	discountDate: timestamp("discount_date", { mode: 'string' }),
	originalImageUrl: text("original_image_url"),
	imageSize: integer("image_size"),
	ocrAnalyzed: boolean("ocr_analyzed").default(false),
	products: jsonb(),
}, (table) => [
	foreignKey({
			columns: [table.martId],
			foreignColumns: [marts.id],
			name: "mart_discounts_mart_id_fkey"
		}),
]);

export const martDiscountItems = pgTable("mart_discount_items", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	discountId: uuid("discount_id").notNull(),
	discountDate: timestamp("discount_date", { mode: 'string' }).notNull(),
	title: text().notNull(),
	description: text(),
	imageUrl: text("image_url"),
	originalImageUrl: text("original_image_url"),
	imageSize: integer("image_size"),
	ocrAnalyzed: boolean("ocr_analyzed").default(false),
	products: jsonb(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	originalProducts: jsonb("original_products"),
}, (table) => [
	index("mart_discount_items_discount_date_idx").using("btree", table.discountDate.asc().nullsLast().op("timestamp_ops")),
	index("mart_discount_items_discount_id_idx").using("btree", table.discountId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.discountId],
			foreignColumns: [martDiscounts.id],
			name: "mart_discount_items_discount_id_fkey"
		}).onDelete("cascade"),
]);

export const weatherLocationKeys = pgTable("weather_location_keys", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	locationName: text("location_name"),
	latitude: text(),
	longitude: text(),
	locationKey: text("location_key").notNull(),
	localizedName: text("localized_name"),
	countryCode: text("country_code"),
	administrativeArea: text("administrative_area"),
	searchType: text("search_type").notNull(),
	rawLocationData: jsonb("raw_location_data"),
	cacheKey: text("cache_key").notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("weather_location_keys_cache_key_unique").on(table.cacheKey),
]);

export const dailyWeatherData = pgTable("daily_weather_data", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	locationKey: text("location_key").notNull(),
	locationName: text("location_name").notNull(),
	latitude: text(),
	longitude: text(),
	forecastDate: text("forecast_date").notNull(),
	dayOfWeek: text("day_of_week").notNull(),
	temperature: integer().notNull(),
	highTemp: integer("high_temp").notNull(),
	lowTemp: integer("low_temp").notNull(),
	conditions: text().notNull(),
	weatherIcon: integer("weather_icon"),
	precipitationProbability: integer("precipitation_probability"),
	rainProbability: integer("rain_probability"),
	dayWeather: jsonb("day_weather"),
	nightWeather: jsonb("night_weather"),
	headline: jsonb(),
	units: text().default('metric').notNull(),
	forecastDays: integer("forecast_days").default(5).notNull(),
	rawData: jsonb("raw_data"),
	cacheKey: text("cache_key").notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	clerkUserId: text("clerk_user_id"),
});

export const hourlyWeatherData = pgTable("hourly_weather_data", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	locationKey: text("location_key").notNull(),
	locationName: text("location_name").notNull(),
	latitude: text(),
	longitude: text(),
	forecastDate: text("forecast_date").notNull(),
	forecastHour: integer("forecast_hour").notNull(),
	forecastDatetime: timestamp("forecast_datetime", { mode: 'string' }).notNull(),
	temperature: integer().notNull(),
	conditions: text().notNull(),
	weatherIcon: integer("weather_icon"),
	humidity: integer(),
	precipitation: text(),
	precipitationProbability: integer("precipitation_probability"),
	rainProbability: integer("rain_probability"),
	windSpeed: integer("wind_speed"),
	units: text().default('metric').notNull(),
	rawData: jsonb("raw_data"),
	cacheKey: text("cache_key").notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
	clerkUserId: text("clerk_user_id"),
});

export const weatherEmbeddings = pgTable("weather_embeddings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	clerkUserId: text("clerk_user_id"),
	contentType: text("content_type").notNull(),
	locationName: text("location_name").notNull(),
	forecastDate: text("forecast_date"),
	forecastHour: integer("forecast_hour"),
	content: text().notNull(),
	embedding: text().notNull(),
	metadata: jsonb(),
	weatherDataId: uuid("weather_data_id"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const chatgptConversations = pgTable("chatgpt_conversations", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	clerkUserId: text("clerk_user_id").notNull(),
	sessionId: text("session_id").notNull(),
	userQuestion: text("user_question").notNull(),
	retrievedContext: jsonb("retrieved_context"),
	gptResponse: text("gpt_response").notNull(),
	tokensUsed: integer("tokens_used"),
	responseTime: integer("response_time"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
});

export const emailSchedules = pgTable("email_schedules", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	title: text().notNull(),
	description: text(),
	emailSubject: text("email_subject").notNull(),
	emailTemplate: text("email_template").notNull(),
	scheduleTime: text("schedule_time").notNull(),
	timezone: text().default('Asia/Seoul').notNull(),
	targetType: text("target_type").default('all_users').notNull(),
	targetUserIds: jsonb("target_user_ids"),
	isActive: boolean("is_active").default(true).notNull(),
	lastSentAt: timestamp("last_sent_at", { mode: 'string' }),
	nextSendAt: timestamp("next_send_at", { mode: 'string' }).notNull(),
	totalSentCount: integer("total_sent_count").default(0).notNull(),
	createdBy: text("created_by").notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
});

export const userEmailSettings = pgTable("user_email_settings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	clerkUserId: text("clerk_user_id").notNull(),
	email: text().notNull(),
	receiveWeatherEmails: boolean("receive_weather_emails").default(true).notNull(),
	receiveMorningEmail: boolean("receive_morning_email").default(true).notNull(),
	receiveEveningEmail: boolean("receive_evening_email").default(true).notNull(),
	preferredLanguage: text("preferred_language").default('ko').notNull(),
	timezone: text().default('Asia/Seoul').notNull(),
	isSubscribed: boolean("is_subscribed").default(true).notNull(),
	unsubscribedAt: timestamp("unsubscribed_at", { mode: 'string' }),
	unsubscribeReason: text("unsubscribe_reason"),
	totalEmailsSent: integer("total_emails_sent").default(0).notNull(),
	lastEmailSentAt: timestamp("last_email_sent_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("user_email_settings_clerk_user_id_unique").on(table.clerkUserId),
]);

export const emailSendLogs = pgTable("email_send_logs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	emailScheduleId: uuid("email_schedule_id"),
	emailType: text("email_type").notNull(),
	subject: text().notNull(),
	recipientCount: integer("recipient_count").notNull(),
	successCount: integer("success_count").notNull(),
	failureCount: integer("failure_count").default(0).notNull(),
	weatherDataUsed: jsonb("weather_data_used"),
	aiSummary: text("ai_summary"),
	forecastPeriod: text("forecast_period"),
	sentAt: timestamp("sent_at", { mode: 'string' }).defaultNow().notNull(),
	executionTime: integer("execution_time"),
	isSuccessful: boolean("is_successful").default(true).notNull(),
	errorMessage: text("error_message"),
	failedEmails: jsonb("failed_emails"),
	initiatedBy: text("initiated_by").notNull(),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.emailScheduleId],
			foreignColumns: [emailSchedules.id],
			name: "email_send_logs_email_schedule_id_email_schedules_id_fk"
		}),
]);

export const individualEmailLogs = pgTable("individual_email_logs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	emailSendLogId: uuid("email_send_log_id").notNull(),
	clerkUserId: text("clerk_user_id").notNull(),
	recipientEmail: text("recipient_email").notNull(),
	subject: text().notNull(),
	emailContent: text("email_content"),
	status: text().notNull(),
	sentAt: timestamp("sent_at", { mode: 'string' }),
	deliveredAt: timestamp("delivered_at", { mode: 'string' }),
	gmailMessageId: text("gmail_message_id"),
	gmailThreadId: text("gmail_thread_id"),
	errorCode: text("error_code"),
	errorMessage: text("error_message"),
	isOpened: boolean("is_opened").default(false),
	openedAt: timestamp("opened_at", { mode: 'string' }),
	isClicked: boolean("is_clicked").default(false),
	clickedAt: timestamp("clicked_at", { mode: 'string' }),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	foreignKey({
			columns: [table.emailSendLogId],
			foreignColumns: [emailSendLogs.id],
			name: "individual_email_logs_email_send_log_id_email_send_logs_id_fk"
		}),
]);
